# This file configures the workflows to trigger in our Prow jobs.
# see https://github.com/kubeflow/testing/blob/master/py/kubeflow/testing/run_e2e_workflow.py
#
# The testWorkerImage should be the same for all workflows.
workflows: []
#   - app_dir: kubeflow/training-operator/test/workflows
#     component: workflows
#     name: v1
#     job_types:
#       - presubmit
#     include_dirs:
#       - build/*
#       - cmd/*
#       - examples/*
#       - hack/*
#       - manifests/*
#       - pkg/*
#       - py/*
#       - scripts/*
#       - sdk/*
#       - test/*
#       - prow_config.yaml
#       - go.*
#     params:
#       registry: "809251082950.dkr.ecr.us-west-2.amazonaws.com/training-operator"
#       tfJobVersion: v1
#       testWorkerImage: public.ecr.aws/j1r0q0g6/kubeflow-testing:latest
#   - app_dir: kubeflow/training-operator/test/workflows
#     component: workflows
#     name: v1
#     job_types:
#       - postsubmit
#     include_dirs:
#       - build/*
#       - cmd/*
#       - examples/*
#       - hack/*
#       - manifests/*
#       - pkg/*
#       - py/*
#       - scripts/*
#       - sdk/*
#       - test/*
#       - prow_config.yaml
#     params:
#       registry: "public.ecr.aws/j1r0q0g6/training/training-operator"
#       tfJobVersion: v1
#       testWorkerImage: public.ecr.aws/j1r0q0g6/kubeflow-testing:latest
