apiVersion: "kubeflow.org/v1"
kind: "MXJob"
metadata:
  name: "mxnet-job"
spec:
  jobMode: MXTrain
  mxReplicaSpecs:
    Scheduler:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: mxnet
              image: mxjob/mxnet:gpu
              ports:
              - containerPort: 9991
                name: mxjob-port
    Server:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: mxnet
              image: mxjob/mxnet:gpu
              ports:
              - containerPort: 9991
                name: mxjob-port
    Worker:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: mxnet
              image: mxjob/mxnet:gpu
              command: ["python"]
              args: ["/incubator-mxnet/example/image-classification/train_mnist.py","--num-epochs","10","--num-layers","2","--kv-store","dist_device_sync","--gpus","0"]
              resources:
                limits:
                  nvidia.com/gpu: 1
              ports:
              - containerPort: 9991
                name: mxjob-port
