apiVersion: "kubeflow.org/v1"
kind: PaddleJob
metadata:
  name: paddle-simple-gpu
  namespace: kubeflow
spec:
  paddleReplicaSpecs:
    Worker:
      replicas: 2
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: paddle
              image: registry.baidubce.com/paddlepaddle/paddle:2.4.0rc0-gpu-cuda11.2-cudnn8.1-trt8.0
              command:
                - python
              args:
                - "-m"
                - paddle.distributed.launch
                - "run_check"
              ports:
                - containerPort: 37777
                  name: master
              imagePullPolicy: Always
              resources:
                  limits:
                      nvidia.com/gpu: 2
              volumeMounts:
                  - mountPath: /dev/shm
                    name: dshm
          volumes:
            - name: dshm
              emptyDir:
                medium: Memory

